User goals
Fiu-Fit/metrics-service pull request #2
Opened 2023-05-09 03:39 UTC by rplatini

2023-05-11 01:25 UTC, ManuSanchez02 requested changes

2023-05-11 01:25 UTC, ManuSanchez02 commented on src/modules/goals/dto/get-goals-query.dto.ts
> +    user?: number;
Es necesario el @Type(() => Number)?

2023-05-11 01:25 UTC, ManuSanchez02 commented on src/modules/goals/dto/get-goals-query.dto.ts
> +
Quizas tambien estaria bueno poder filtrar segun el ejercicio (quizas me estoy adelantando un poco a los requisitos del front), no se que opinas?

2023-05-11 01:25 UTC, ManuSanchez02 commented on src/modules/goals/interfaces/goal.interface.ts
> +}
Estaria bueno tener esto en common

2023-05-11 01:28 UTC, ManuSanchez02 requested changes

2023-05-11 01:28 UTC, ManuSanchez02 commented on src/modules/goals/goal.service.ts
> +    const updatedGoalDto = new GoalDTO;
Es necesario instanciar un GoalDTO? No podes modificar el goal que te pasan por parametro? Me suena medio raro instanciar un DTO asi, igual le pregunto a alguno de los chicos de ultima

2023-05-11 02:08 UTC, ianshih2003 requested changes

2023-05-11 02:08 UTC, ianshih2003 commented on src/modules/goals/dto/get-goals-query.dto.ts
> +    user?: number;
cambiemos el nombre a userId

2023-05-11 02:08 UTC, ianshih2003 commented on src/modules/goals/goal.service.ts
> +    return createdGoal;
podes devolver directamente la promise

2023-05-11 02:08 UTC, ianshih2003 commented on src/modules/goals/goal.service.ts
> +    }).then(goals => Promise.all(goals.map(goal => this.checkGoalStatus(goal))));
En vez del .then, podes hacer `return Promise.all(goals.map(goal => this.checkGoalStatus(goal))`

2023-05-11 02:08 UTC, ianshih2003 commented on src/modules/goals/goal.service.ts
> +  }
Se podrian hacer en el mismo metodo,
por ejemplo,

```
findMany({
    ...(filter ? { where: filter } : {})
})
```
Cuando no hay filter, no agrega el where
PD: Solo funcionaria si cambias el nombre del filter

2023-05-11 02:08 UTC, ianshih2003 commented on src/modules/goals/goal.service.ts
> +    const goal = this.prismaService.goal.delete({
No es necesaria la variable

2023-05-11 02:08 UTC, ianshih2003 commented on src/modules/goals/goal.service.ts
> +    });
Podemos usar el metodo `sumBy` de `lodash`

2023-05-11 02:08 UTC, ianshih2003 commented on src/modules/goals/goal.service.ts
> +    }
Podemos usar early return

2023-05-11 02:08 UTC, ianshih2003 commented on src/modules/goals/goal.service.ts
> +    Object.assign(updatedGoalDto, { ...goal, status });
Suena raro usar Object.assign, no podias pasar el mismo objeto?

```
return this.editGoal(
      goal.id, 
      { ...goal, status }
    );   
```

2023-05-11 02:08 UTC, ianshih2003 commented on src/modules/goals/interfaces/goal.interface.ts
> +}
No lo genera prisma?

2023-05-11 02:36 UTC, rplatini commented on src/modules/goals/dto/get-goals-query.dto.ts
> +    user?: number;
Creo que si, cuando no tenia puesto ese decorator me tiraba un error de que el input igresado no era un numero. No se si hay alguna otra opcion

2023-05-11 02:37 UTC, rplatini commented on src/modules/goals/dto/get-goals-query.dto.ts
> +
Si dale, lo puedo agregar

2023-05-11 02:37 UTC, rplatini commented on src/modules/goals/interfaces/goal.interface.ts
> +}
para usarlo en otro microservicio decis?

2023-05-11 02:39 UTC, rplatini commented on src/modules/goals/dto/get-goals-query.dto.ts
> +    user?: number;
habia hablado con Manu de que los fields como `userId` o `exerciseId` quedaran simplemente sin el sufijo `id`, pongamonos de acuerdo jajaj

2023-05-11 02:50 UTC, ManuSanchez02 commented on src/modules/goals/interfaces/goal.interface.ts
> +}
Si, y en el front tambien

2023-05-11 02:51 UTC, ManuSanchez02 commented on src/modules/goals/dto/get-goals-query.dto.ts
> +    user?: number;
Jajajajjaaj bueno dale, pongamosle id a todo asi podemos hacer esto que dijo ian
```
findMany({
    ...(filter ? { where: filter } : {})
})
```

2023-05-11 02:52 UTC, ManuSanchez02 commented on src/modules/goals/dto/get-goals-query.dto.ts
> +    user?: number;
Ahora abro un pr en el que cambio los nombres para las querys de las metricas

2023-05-11 02:52 UTC, ManuSanchez02 commented on src/modules/goals/goal.service.ts
> +  }
Es mas, creo que si los campos del filtro son undefined, los ignora

2023-05-11 03:00 UTC, ManuSanchez02 commented on src/modules/goals/dto/get-goals-query.dto.ts
> +    user?: number;
Hago un poco de spam https://github.com/Fiu-Fit/metrics-service/pull/3

2023-05-11 03:34 UTC, rplatini commented on src/modules/goals/goal.service.ts
> +    Object.assign(updatedGoalDto, { ...goal, status });
Si, intente no tener que hacer un objeto nuevo, incluso como me sugeris ahi. El tema es que el field deadline es opcional, y me tira el error de que no se puede asignar un tipo null. Todavia no lo pude resolver

2023-05-11 03:35 UTC, rplatini commented on src/modules/goals/goal.service.ts
> +    const updatedGoalDto = new GoalDTO;
Mas abajo ian me dijo lo mismo

2023-05-11 03:39 UTC, rplatini commented on src/modules/goals/interfaces/goal.interface.ts
> +}
efectivamente

2023-05-11 12:44 UTC, rplatini commented on src/modules/goals/interfaces/goal.interface.ts
> +}
dale

2023-05-11 18:14 UTC, manusfv approved these changes

2023-05-11 18:14 UTC, ManuSanchez02 commented on package.json
> +    "@fiu-fit/common": "ssh://git@github.com:Fiu-Fit/common.git",
Funciona con ssh?

2023-05-11 18:14 UTC, ManuSanchez02 approved these changes

2023-05-11 19:00 UTC, rplatini commented on package.json
> +    "@fiu-fit/common": "ssh://git@github.com:Fiu-Fit/common.git",
Sinceramente no tengo idea, ejecute el comando `common:install` y se actualizo. Y como las interfaces no se usan en el back, no lo probe. Habia algun problema con ssh? lo vuelvo a cambiar sino

2023-05-11 19:28 UTC, ianshih2003 requested changes

2023-05-11 19:28 UTC, ianshih2003 commented on src/modules/goals/goal.service.ts
> +    filter.start = new Date(goal.createdAt).toISOString();
creo que manu renombro esto

2023-05-11 19:28 UTC, ianshih2003 commented on src/modules/goals/goal.service.ts
> +    Object.assign(updatedGoalDto, { ...goal, status });
Manda el error en especifico

2023-05-11 19:49 UTC, rplatini commented on src/modules/goals/goal.service.ts
> +    Object.assign(updatedGoalDto, { ...goal, status });
```
Argument of type '{ status: GoalStatus; id: number; title: string; description: string; userId: number; targetValue: number; deadline: Date | null; createdAt: Date; exerciseId: string; }' is not assignable to parameter of type 'GoalDto'.
  Types of property 'deadline' are incompatible.
    Type 'Date | null' is not assignable to type 'Date'.
      Type 'null' is not assignable to type 'Date'.
```

2023-05-11 19:53 UTC, rplatini commented on src/modules/goals/goal.service.ts
> +    Object.assign(updatedGoalDto, { ...goal, status });
Pude fixearlo si al servicio `editGoal` le paso un `Goal` como parametro en vez de un `GoalDto`. Te parece bien que haga esto?

2023-05-16 03:23 UTC, ianshih2003 approved these changes

2023-05-16 03:23 UTC, merged